/* eslint-disable */
// ==========================================
// ⚠️ 自动生成，勿手动编辑
// 生成时间: 2026-09-02T10:49:25.682Z
// 数据源: configs/attributes/attributes.json
// 配置修改后请重新运行: npm run generate:attributes
// ==========================================

import type { AttributeMeta } from './types'

export const ATTRIBUTE_CODE = {
  currentHealth: 'currentHealth',
  maxHealth: 'maxHealth',
  attack: 'attack',
  defense: 'defense',
  speed: 'speed',
  critRate: 'critRate',
  critDamage: 'critDamage',
  currentEnergy: 'currentEnergy',
  maxEnergy: 'maxEnergy',
  damageReduction: 'damageReduction',
  normalAtkDmgReduction: 'normalAtkDmgReduction',
  skillDmgReduction: 'skillDmgReduction',
  critDmgTakenReduction: 'critDmgTakenReduction',
  hpRegenPercent: 'hpRegenPercent',
  hpRegenFlat: 'hpRegenFlat',
  healthBonus: 'healthBonus',
  attackBonus: 'attackBonus',
  defenseBonus: 'defenseBonus',
  speedBonus: 'speedBonus',
  hitValue: 'hitValue',
  dodgeValue: 'dodgeValue',
  dodge: 'dodge',
  hit: 'hit',
  controlSuccessRate: 'controlSuccessRate',
  controlDurationReduction: 'controlDurationReduction',
  damageTakenIncrease: 'damageTakenIncrease',
  damageBoost: 'damageBoost',
  poisonRes: 'poisonRes',
  fireSkillDmgBonus: 'fireSkillDmgBonus',
  physicalSkillDmgBonus: 'physicalSkillDmgBonus',
  damageToDemon: 'damageToDemon',
  damageToLowHp: 'damageToLowHp',
  shield: 'shield',
  reflectDamagePercent: 'reflectDamagePercent',
  debuffImmunityRate: 'debuffImmunityRate',
  demonDamage: 'demonDamage',
  skillCooldown: 'skillCooldown',
  critDamageTaken: 'critDamageTaken',
  burnDuration: 'burnDuration',
  fireDamage: 'fireDamage',
  fireDamageTaken: 'fireDamageTaken',
  waterDamageTaken: 'waterDamageTaken',
  lightningDamageTaken: 'lightningDamageTaken',
  webSuccessRate: 'webSuccessRate',
  trueDamageRate: 'trueDamageRate',
  healReceived: 'healReceived',
  comboRate: 'comboRate',
  counterRate: 'counterRate',
  damageDealt: 'damageDealt',
  damageTaken: 'damageTaken',
  energyInit: 'energyInit',
  lifestealRate: 'lifestealRate',
  hitBonus: 'hitBonus',
  dodgeBonus: 'dodgeBonus',
  healthCoefficient: 'healthCoefficient',
  attackCoefficient: 'attackCoefficient',
  defenseCoefficient: 'defenseCoefficient',
  hitCoefficient: 'hitCoefficient',
  dodgeCoefficient: 'dodgeCoefficient',
  speedCoefficient: 'speedCoefficient',
  finalAttack: 'finalAttack',
  finalDefense: 'finalDefense',
  normalAtkBonus: 'normalAtkBonus',
  skillBonus: 'skillBonus',
  counterDamageBonus: 'counterDamageBonus',
  damageCoefficient: 'damageCoefficient',
  counterDamageCoefficient: 'counterDamageCoefficient',
  comboDamageCoefficient: 'comboDamageCoefficient',
  trueDamageCoefficient: 'trueDamageCoefficient',
  finalDamageBoost: 'finalDamageBoost',
  damageReductionCoefficient: 'damageReductionCoefficient',
  finalDamageReduction: 'finalDamageReduction',
  critResist: 'critResist',
  trueDamageResist: 'trueDamageResist',
  controlImmunity: 'controlImmunity',
  effectHit: 'effectHit',
  energyGainEfficiency: 'energyGainEfficiency',
  splash: 'splash',
  armorBreak: 'armorBreak',
  vulnerability: 'vulnerability',
  shieldBonus: 'shieldBonus',
  shieldReduction: 'shieldReduction',
  reflectBonus: 'reflectBonus',
  reflectReduction: 'reflectReduction',
  lifestealBonus: 'lifestealBonus',
  lifestealReduction: 'lifestealReduction',
  healBonus: 'healBonus',
  healReduction: 'healReduction',
  waterAtk: 'waterAtk',
  fireAtk: 'fireAtk',
  metalAtk: 'metalAtk',
  woodAtk: 'woodAtk',
  earthAtk: 'earthAtk',
  metalRes: 'metalRes',
  woodRes: 'woodRes',
  waterRes: 'waterRes',
  fireRes: 'fireRes',
  earthRes: 'earthRes',
} as const

export type ATTRIBUTE_CODE = (typeof ATTRIBUTE_CODE)[keyof typeof ATTRIBUTE_CODE]

export const AttributeMetaMap: Record<ATTRIBUTE_CODE, AttributeMeta> = {
  currentHealth: {
    code: 'currentHealth',
    name: '当前气血',
    displayName: '当前气血',
    description: '角色当前气血',
    isPercentage: false,
    range: '0-最大值',
    impact: '直接影响角色生存能力，为0时角色死亡',
    isRuntimeState: true,
  },
  maxHealth: {
    code: 'maxHealth',
    name: '最大气血',
    displayName: '最大气血',
    description: '最大气血上限',
    isPercentage: false,
    range: '1-99999',
    impact: '决定角色的气血上限，影响生存能力',
  },
  attack: {
    code: 'attack',
    name: '攻击力',
    displayName: '攻击力',
    description: '角色基础攻击力，直接影响伤害输出',
    isPercentage: false,
    range: '1-9999',
    impact: '直接影响伤害输出，是计算最终伤害的基础',
  },
  defense: {
    code: 'defense',
    name: '防御力',
    displayName: '防御力',
    description: '角色抵抗伤害的能力',
    isPercentage: false,
    range: '0-9999',
    impact: '减少受到的伤害，值越高减伤越多',
  },
  speed: {
    code: 'speed',
    name: '速度',
    displayName: '速度',
    description: '角色行动顺序的决定因素',
    isPercentage: false,
    range: '1-9999',
    impact: '速度越高，行动顺序越靠前，回合内行动次数可能增加',
  },
  critRate: {
    code: 'critRate',
    name: '暴击率',
    displayName: '暴击率',
    description: '攻击产生暴击的概率',
    isPercentage: true,
    defaultValue: 10,
    range: '0-100%',
    impact: '提高暴击触发几率，增加伤害爆发能力，默认为10%',
  },
  critDamage: {
    code: 'critDamage',
    name: '暴击伤害',
    displayName: '暴击伤害',
    description: '暴击时的伤害倍率',
    isPercentage: true,
    defaultValue: 125,
    range: '100-500%',
    impact: '暴击时造成的额外伤害，值越高暴击伤害越高，默认125%',
  },
  currentEnergy: {
    code: 'currentEnergy',
    name: '当前能量',
    displayName: '当前能量',
    description: '角色当前能量值',
    isPercentage: false,
    defaultValue: 30,
    range: '0-200',
    impact: '用于施放技能，影响技能释放频率，初始值为30',
    isRuntimeState: true,
  },
  maxEnergy: {
    code: 'maxEnergy',
    name: '最大能量',
    displayName: '最大能量',
    description: '最大能量上限',
    isPercentage: false,
    defaultValue: 200,
    range: '200',
    impact: '决定能量上限，通常固定为200',
  },
  damageReduction: {
    code: 'damageReduction',
    name: '免伤率',
    displayName: '免伤率',
    description: '受到伤害的通用减免比例',
    isPercentage: true,
    range: '0-100%',
    impact: '减少受到的所有类型伤害',
  },
  normalAtkDmgReduction: {
    code: 'normalAtkDmgReduction',
    name: '普攻伤害减免',
    displayName: '普攻伤害减免',
    description: '仅对普通攻击有效的伤害减免',
    isPercentage: true,
    range: '0-100%',
    impact: '专门减少普通攻击造成的伤害',
  },
  skillDmgReduction: {
    code: 'skillDmgReduction',
    name: '技能伤害减免',
    displayName: '技能伤害减免',
    description: '仅对技能攻击有效的伤害减免',
    isPercentage: true,
    range: '0-100%',
    impact: '专门减少技能攻击造成的伤害',
  },
  critDmgTakenReduction: {
    code: 'critDmgTakenReduction',
    name: '暴击承伤减免',
    displayName: '暴击承伤减免',
    description: '受到暴击时的额外伤害减免',
    isPercentage: true,
    range: '0-100%',
    impact: '减少暴击时受到的额外伤害，提高抗暴能力',
  },
  hpRegenPercent: {
    code: 'hpRegenPercent',
    name: '气血回复(%)',
    displayName: '百分比气血回复',
    description: '每回合恢复最大气血的百分比',
    isPercentage: true,
    range: '0-50%',
    impact: '按最大气血百分比回复气血，适合高血量角色',
  },
  hpRegenFlat: {
    code: 'hpRegenFlat',
    name: '气血回复(固定)',
    displayName: '固定气血回复',
    description: '每回合恢复固定的气血',
    isPercentage: false,
    range: '0-9999',
    impact: '每回合回复固定数值的气血',
  },
  healthBonus: {
    code: 'healthBonus',
    name: '气血加成',
    displayName: '气血加成',
    description: '基于基础气血的加成百分比',
    isPercentage: true,
    range: '0-500%',
    impact: '按百分比提高最大气血上限',
  },
  attackBonus: {
    code: 'attackBonus',
    name: '攻击力加成',
    displayName: '攻击力加成',
    description: '基于基础攻击力的加成百分比',
    isPercentage: true,
    range: '0-500%',
    impact: '按百分比提高攻击力',
  },
  defenseBonus: {
    code: 'defenseBonus',
    name: '防御力加成',
    displayName: '防御力加成',
    description: '基于基础防御力的加成百分比',
    isPercentage: true,
    range: '0-500%',
    impact: '按百分比提高防御力',
  },
  speedBonus: {
    code: 'speedBonus',
    name: '速度加成',
    displayName: '速度加成',
    description: '基于基础速度的加成百分比',
    isPercentage: true,
    range: '0-500%',
    impact: '按百分比提高速度',
  },
  hitValue: {
    code: 'hitValue',
    name: '命中值',
    displayName: '命中值',
    description: '攻击方的命中基础值，用于对抗防御方闪避值计算基础命中率',
    isPercentage: false,
    defaultValue: 100,
    range: '0-99999',
    impact: '命中值越高，基础命中率越高，对抗敌方闪避值',
  },
  dodgeValue: {
    code: 'dodgeValue',
    name: '闪避值',
    displayName: '闪避值',
    description: '防御方的闪避基础值，用于对抗攻击方命中值计算基础命中率',
    isPercentage: false,
    defaultValue: 0,
    range: '0-99999',
    impact: '闪避值越高，基础命中率越低，提高生存能力',
  },
  dodge: {
    code: 'dodge',
    name: '闪避率',
    displayName: '闪避率',
    description: '完全躲避攻击的概率（进阶属性，作为命中公式修正项）',
    isPercentage: true,
    defaultValue: 10,
    range: '0-75%',
    impact: '有概率完全避免受到伤害，命中公式中作为减项',
  },
  hit: {
    code: 'hit',
    name: '命中率',
    displayName: '命中率',
    description: '攻击命中目标的概率（进阶属性，作为命中公式修正项）',
    isPercentage: true,
    defaultValue: 90,
    range: '0-100%',
    impact: '提高攻击命中率，命中公式中作为加项',
  },
  controlSuccessRate: {
    code: 'controlSuccessRate',
    name: '控制成功率',
    displayName: '控制技能成功率',
    description: '控制类技能（眩晕、沉默等）的成功率',
    isPercentage: true,
    range: '0-100%',
    impact: '提高控制效果施加成功的概率',
  },
  controlDurationReduction: {
    code: 'controlDurationReduction',
    name: '控制时间减免',
    displayName: '受控制时间减免',
    description: '减少被控制状态影响的持续时间',
    isPercentage: true,
    range: '0-100%',
    impact: '降低被眩晕、沉默等控制的持续时间',
  },
  damageTakenIncrease: {
    code: 'damageTakenIncrease',
    name: '易伤',
    displayName: '受到伤害增加',
    description: '受到的所有伤害增加的比例（易伤状态）',
    isPercentage: true,
    range: '0-200%',
    impact: '增加受到的伤害，通常由debuff引起',
  },
  damageBoost: {
    code: 'damageBoost',
    name: '伤害提升',
    displayName: '伤害提升',
    description: '造成伤害的通用加成比例',
    isPercentage: true,
    range: '0-200%',
    impact: '提高造成的所有类型伤害',
  },
  poisonRes: {
    code: 'poisonRes',
    name: '毒素抗性',
    displayName: '毒素抗性',
    description: '对毒素效果的抵抗力',
    isPercentage: true,
    range: '0-100%',
    impact: '减少中毒效果的持续时间和伤害',
  },
  fireSkillDmgBonus: {
    code: 'fireSkillDmgBonus',
    name: '火系技能伤害加成',
    displayName: '火系技能伤害加成',
    description: '火属性技能造成的额外伤害百分比',
    isPercentage: true,
    range: '0-200%',
    impact: '提高火属性技能的伤害输出',
  },
  physicalSkillDmgBonus: {
    code: 'physicalSkillDmgBonus',
    name: '物理技能伤害加成',
    displayName: '物理技能伤害加成',
    description: '物理技能造成的额外伤害百分比',
    isPercentage: true,
    range: '0-200%',
    impact: '提高物理技能的伤害输出',
  },
  damageToDemon: {
    code: 'damageToDemon',
    name: '对妖伤害加成',
    displayName: '对妖魔鬼怪伤害加成',
    description: '对妖魔鬼怪类敌人造成的额外伤害百分比',
    isPercentage: true,
    range: '0-200%',
    impact: '提高对妖魔鬼怪类敌人的伤害',
  },
  damageToLowHp: {
    code: 'damageToLowHp',
    name: '对低血量伤害加成',
    displayName: '对低血量目标伤害加成',
    description: '对气血低于一定比例的目标造成的额外伤害百分比',
    isPercentage: true,
    range: '0-200%',
    impact: '提高对低血量目标的伤害输出',
  },
  shield: {
    code: 'shield',
    name: '护盾值',
    displayName: '护盾值',
    description: '当前护盾值，受到伤害时优先消耗护盾',
    isPercentage: false,
    range: '0-99999',
    impact: '吸收受到的伤害，护盾归零后开始消耗气血',
    isRuntimeState: true,
  },
  reflectDamagePercent: {
    code: 'reflectDamagePercent',
    name: '伤害反弹',
    displayName: '反弹伤害比例',
    description: '将受到的伤害按比例反弹给攻击者',
    isPercentage: true,
    range: '0-100%',
    impact: '受到伤害时反弹部分伤害给攻击者',
  },
  debuffImmunityRate: {
    code: 'debuffImmunityRate',
    name: '减益免疫率',
    displayName: '减益免疫率',
    description: '抵抗减益效果的概率',
    isPercentage: true,
    range: '0-100%',
    impact: '百分比抵抗减益',
  },
  demonDamage: {
    code: 'demonDamage',
    name: '妖魔鬼怪伤害',
    displayName: '妖魔鬼怪伤害',
    description: '对妖魔鬼怪类型敌人的伤害加成',
    isPercentage: false,
    range: '0-99999',
    impact: '提高对妖魔的伤害',
  },
  skillCooldown: {
    code: 'skillCooldown',
    name: '技能冷却',
    displayName: '技能冷却',
    description: '技能冷却缩减（正数为减少，负数为增加）',
    isPercentage: false,
    range: '-99-99',
    impact: '影响技能冷却回合',
  },
  critDamageTaken: {
    code: 'critDamageTaken',
    name: '受到暴击伤害',
    displayName: '受到暴击伤害',
    description: '受到暴击时额外承受的伤害比例',
    isPercentage: true,
    range: '0-100%',
    impact: '提高暴击所受伤害',
  },
  burnDuration: {
    code: 'burnDuration',
    name: '灼烧持续时间',
    displayName: '灼烧持续时间',
    description: '灼烧效果的持续回合数',
    isPercentage: false,
    range: '0-99',
    impact: '增加或减少灼烧回合',
  },
  fireDamage: {
    code: 'fireDamage',
    name: '火属性伤害',
    displayName: '火属性伤害',
    description: '火属性伤害数值（区别于百分比加成）',
    isPercentage: false,
    range: '0-99999',
    impact: '提高火系技能伤害',
  },
  fireDamageTaken: {
    code: 'fireDamageTaken',
    name: '受到火属性伤害',
    displayName: '受到火属性伤害',
    description: '受到火属性伤害时额外承受的数值',
    isPercentage: true,
    range: '0-100%',
    impact: '提高所受火伤',
  },
  waterDamageTaken: {
    code: 'waterDamageTaken',
    name: '受到水属性伤害',
    displayName: '受到水属性伤害',
    description: '受到水属性伤害时额外承受的数值',
    isPercentage: true,
    range: '0-100%',
    impact: '提高所受水伤',
  },
  lightningDamageTaken: {
    code: 'lightningDamageTaken',
    name: '受到雷属性伤害',
    displayName: '受到雷属性伤害',
    description: '受到雷属性伤害时额外承受的数值',
    isPercentage: true,
    range: '0-100%',
    impact: '提高所受雷伤',
  },
  webSuccessRate: {
    code: 'webSuccessRate',
    name: '蛛网成功率',
    displayName: '蛛网成功率',
    description: '蛛网类技能成功概率',
    isPercentage: true,
    range: '0-100%',
    impact: '影响蛛网控制命中率',
  },
  trueDamageRate: {
    code: 'trueDamageRate',
    name: '真实伤害率',
    displayName: '真实伤害率',
    description: '造成真实伤害的比例，忽略防御和免伤',
    isPercentage: true,
    range: '0-100%',
    impact: '造成无视防御的伤害',
  },
  healReceived: {
    code: 'healReceived',
    name: '受到治疗加成',
    displayName: '受到治疗加成',
    description: '受到治疗效果的比例修正',
    isPercentage: true,
    range: '0-100%',
    impact: '影响所受治疗量',
  },
  comboRate: {
    code: 'comboRate',
    name: '连击率',
    displayName: '连击率',
    description: '普通攻击触发额外连击的概率',
    isPercentage: true,
    range: '0-100%',
    impact: '提高额外攻击次数',
  },
  counterRate: {
    code: 'counterRate',
    name: '反击率',
    displayName: '反击率',
    description: '受到攻击时触发反击的概率',
    isPercentage: true,
    range: '0-100%',
    impact: '提高反击触发几率',
  },
  damageDealt: {
    code: 'damageDealt',
    name: '造成伤害',
    displayName: '造成伤害',
    description: '本次攻击造成的伤害值（上下文值，用于技能链计算）',
    isPercentage: false,
    range: '0-99999',
    impact: '作为技能公式输入',
  },
  damageTaken: {
    code: 'damageTaken',
    name: '受到伤害',
    displayName: '受到伤害',
    description: '本次受到的伤害值（上下文值，用于技能链计算）',
    isPercentage: false,
    range: '0-99999',
    impact: '作为技能公式输入',
  },
  energyInit: {
    code: 'energyInit',
    name: '初始能量',
    displayName: '初始能量',
    description: '战斗开始时角色拥有的能量',
    isPercentage: false,
    defaultValue: 30,
    range: '0-200',
    impact: '决定首回合能否释放技能',
  },
  lifestealRate: {
    code: 'lifestealRate',
    name: '吸血率',
    displayName: '吸血率',
    description: '造成伤害时按比例回复气血',
    isPercentage: true,
    range: '0-100%',
    impact: '提高吸血能力，造成伤害时按比例恢复气血',
  },
  hitBonus: {
    code: 'hitBonus',
    name: '命中加成',
    displayName: '命中加成',
    description: '按百分比提高命中',
    isPercentage: true,
    range: '0-100%',
    impact: '百分比提高命中值',
  },
  dodgeBonus: {
    code: 'dodgeBonus',
    name: '闪避加成',
    displayName: '闪避加成',
    description: '按百分比提高闪避',
    isPercentage: true,
    range: '0-100%',
    impact: '百分比提高闪避值',
  },
  healthCoefficient: {
    code: 'healthCoefficient',
    name: '气血系数',
    displayName: '气血系数',
    description: '对气血进行独立乘区放大',
    isPercentage: true,
    range: '0-60%',
    impact: '独立乘区放大最大气血',
  },
  attackCoefficient: {
    code: 'attackCoefficient',
    name: '攻击系数',
    displayName: '攻击系数',
    description: '对攻击进行独立乘区放大',
    isPercentage: true,
    range: '0-60%',
    impact: '独立乘区放大攻击力',
  },
  defenseCoefficient: {
    code: 'defenseCoefficient',
    name: '防御系数',
    displayName: '防御系数',
    description: '对防御进行独立乘区放大',
    isPercentage: true,
    range: '0-60%',
    impact: '独立乘区放大防御力',
  },
  hitCoefficient: {
    code: 'hitCoefficient',
    name: '命中系数',
    displayName: '命中系数',
    description: '对命中进行独立乘区放大',
    isPercentage: true,
    range: '0-60%',
    impact: '独立乘区放大命中值',
  },
  dodgeCoefficient: {
    code: 'dodgeCoefficient',
    name: '闪避系数',
    displayName: '闪避系数',
    description: '对闪避进行独立乘区放大',
    isPercentage: true,
    range: '0-60%',
    impact: '独立乘区放大闪避值',
  },
  speedCoefficient: {
    code: 'speedCoefficient',
    name: '速度系数',
    displayName: '速度系数',
    description: '对速度进行独立乘区放大',
    isPercentage: true,
    range: '0-60%',
    impact: '独立乘区放大速度',
  },
  finalAttack: {
    code: 'finalAttack',
    name: '最终攻击',
    displayName: '最终攻击',
    description: '最终层提高攻击，不被任何乘区稀释',
    isPercentage: true,
    range: '0-60%',
    impact: '最终乘区提高攻击',
  },
  finalDefense: {
    code: 'finalDefense',
    name: '最终防御',
    displayName: '最终防御',
    description: '最终层提高防御，不被任何乘区稀释',
    isPercentage: true,
    range: '0-60%',
    impact: '最终乘区提高防御',
  },
  normalAtkBonus: {
    code: 'normalAtkBonus',
    name: '普攻加成',
    displayName: '普攻加成',
    description: '仅按百分比提高普攻伤害',
    isPercentage: true,
    range: '0-100%',
    impact: '提高普攻伤害',
  },
  skillBonus: {
    code: 'skillBonus',
    name: '技能加成',
    displayName: '技能加成',
    description: '仅按百分比提高技能伤害',
    isPercentage: true,
    range: '0-50%',
    impact: '提高技能伤害',
  },
  counterDamageBonus: {
    code: 'counterDamageBonus',
    name: '反击伤害加成',
    displayName: '反击伤害加成',
    description: '仅按百分比提高反击的伤害',
    isPercentage: true,
    range: '0-150%',
    impact: '提高反击伤害',
  },
  damageCoefficient: {
    code: 'damageCoefficient',
    name: '伤害系数',
    displayName: '伤害系数',
    description: '对造成的伤害进行独立乘区放大',
    isPercentage: true,
    range: '0-150%',
    impact: '独立乘区放大造成伤害',
  },
  counterDamageCoefficient: {
    code: 'counterDamageCoefficient',
    name: '反击伤害系数',
    displayName: '反击伤害系数',
    description: '独立放大反击段的伤害',
    isPercentage: true,
    range: '0-150%',
    impact: '独立乘区放大反击伤害',
  },
  comboDamageCoefficient: {
    code: 'comboDamageCoefficient',
    name: '连击伤害系数',
    displayName: '连击伤害系数',
    description: '独立放大连击段的伤害',
    isPercentage: true,
    range: '0-150%',
    impact: '独立乘区放大连击伤害',
  },
  trueDamageCoefficient: {
    code: 'trueDamageCoefficient',
    name: '真伤系数',
    displayName: '真伤系数',
    description: '独立放大真实伤害',
    isPercentage: true,
    range: '0-150%',
    impact: '独立乘区放大真实伤害',
  },
  finalDamageBoost: {
    code: 'finalDamageBoost',
    name: '最终伤害提升',
    displayName: '最终伤害提升',
    description: '最终层提高造成的伤害',
    isPercentage: true,
    range: '0-150%',
    impact: '最终乘区提高造成伤害',
  },
  damageReductionCoefficient: {
    code: 'damageReductionCoefficient',
    name: '免伤系数',
    displayName: '免伤系数',
    description: '独立放大免伤效果',
    isPercentage: true,
    range: '0-50%',
    impact: '独立乘区放大免伤率',
  },
  finalDamageReduction: {
    code: 'finalDamageReduction',
    name: '最终伤害减免',
    displayName: '最终伤害减免',
    description: '最终层减少受到的伤害',
    isPercentage: true,
    range: '0-40%',
    impact: '最终乘区减少受到伤害',
  },
  critResist: {
    code: 'critResist',
    name: '暴击抵抗',
    displayName: '暴击抵抗',
    description: '降低敌方对自己的暴击率',
    isPercentage: true,
    range: '0-55%',
    impact: '降低被暴击概率',
  },
  trueDamageResist: {
    code: 'trueDamageResist',
    name: '真伤抗性',
    displayName: '真伤抗性',
    description: '减少受到的真实伤害',
    isPercentage: true,
    range: '0-62%',
    impact: '减少受到的真实伤害',
  },
  controlImmunity: {
    code: 'controlImmunity',
    name: '控制豁免',
    displayName: '控制豁免',
    description: '降低被敌方控制的概率',
    isPercentage: true,
    range: '0-62%',
    impact: '降低被控制概率',
  },
  effectHit: {
    code: 'effectHit',
    name: '效果命中',
    displayName: '效果命中',
    description: '提高减益与异常状态的命中概率',
    isPercentage: true,
    range: '0-50%',
    impact: '提高减益与异常状态命中率',
  },
  energyGainEfficiency: {
    code: 'energyGainEfficiency',
    name: '能量获取效率',
    displayName: '能量获取效率',
    description: '按百分比放大所有来源获得的能量',
    isPercentage: true,
    range: '0-100%',
    impact: '放大能量获取',
  },
  splash: {
    code: 'splash',
    name: '溅射',
    displayName: '溅射',
    description: '攻击主目标时对相邻目标造成的伤害比例',
    isPercentage: true,
    range: '0-200%',
    impact: '对相邻目标造成溅射伤害',
  },
  armorBreak: {
    code: 'armorBreak',
    name: '破甲',
    displayName: '破甲',
    description: '降低目标防御，可叠加层数',
    isPercentage: true,
    range: '0-50%',
    impact: '降低目标防御',
  },
  vulnerability: {
    code: 'vulnerability',
    name: '易伤',
    displayName: '易伤',
    description: '提高目标受到的伤害',
    isPercentage: true,
    range: '0-100%',
    impact: '提高目标承伤',
  },
  shieldBonus: {
    code: 'shieldBonus',
    name: '护盾加成',
    displayName: '护盾加成',
    description: '放大所有来源提供的护盾值',
    isPercentage: true,
    range: '0-100%',
    impact: '放大护盾值',
  },
  shieldReduction: {
    code: 'shieldReduction',
    name: '护盾削减',
    displayName: '护盾削减',
    description: '降低目标获得的护盾值',
    isPercentage: true,
    range: '0-50%',
    impact: '降低目标护盾值',
  },
  reflectBonus: {
    code: 'reflectBonus',
    name: '伤害反弹加成',
    displayName: '伤害反弹加成',
    description: '放大反弹伤害的数值',
    isPercentage: true,
    range: '0-300%',
    impact: '放大反弹伤害',
  },
  reflectReduction: {
    code: 'reflectReduction',
    name: '伤害反弹削减',
    displayName: '伤害反弹削减',
    description: '降低目标反弹伤害的数值',
    isPercentage: true,
    range: '0-50%',
    impact: '降低目标反弹伤害',
  },
  lifestealBonus: {
    code: 'lifestealBonus',
    name: '吸血效果加成',
    displayName: '吸血效果加成',
    description: '放大吸血回复量',
    isPercentage: true,
    range: '0-100%',
    impact: '放大吸血回复量',
  },
  lifestealReduction: {
    code: 'lifestealReduction',
    name: '吸血效果削减',
    displayName: '吸血效果削减',
    description: '降低目标吸血的回复量',
    isPercentage: true,
    range: '0-50%',
    impact: '降低目标吸血回复量',
  },
  healBonus: {
    code: 'healBonus',
    name: '治疗强度加成',
    displayName: '治疗强度加成',
    description: '放大提供的治疗效果',
    isPercentage: true,
    range: '0-100%',
    impact: '放大治疗效果',
  },
  healReduction: {
    code: 'healReduction',
    name: '治疗强度削减',
    displayName: '治疗强度削减',
    description: '降低目标受到的治疗效果',
    isPercentage: true,
    range: '0-50%',
    impact: '降低目标受到的治疗效果',
  },
  waterAtk: {
    code: 'waterAtk',
    name: '水属性攻击',
    displayName: '水属性攻击力',
    description: '水元素属性攻击力',
    isPercentage: false,
    range: '0-9999',
    impact: '对火属性敌人造成额外伤害',
  },
  fireAtk: {
    code: 'fireAtk',
    name: '火属性攻击',
    displayName: '火属性攻击力',
    description: '火元素属性攻击力',
    isPercentage: false,
    range: '0-9999',
    impact: '对金属性敌人造成额外伤害',
  },
  metalAtk: {
    code: 'metalAtk',
    name: '金属性攻击',
    displayName: '金属性攻击力',
    description: '金元素属性攻击力',
    isPercentage: false,
    range: '0-9999',
    impact: '对木属性敌人造成额外伤害',
  },
  woodAtk: {
    code: 'woodAtk',
    name: '木属性攻击',
    displayName: '木属性攻击力',
    description: '木元素属性攻击力',
    isPercentage: false,
    range: '0-9999',
    impact: '对土属性敌人造成额外伤害',
  },
  earthAtk: {
    code: 'earthAtk',
    name: '土属性攻击',
    displayName: '土属性攻击力',
    description: '土元素属性攻击力',
    isPercentage: false,
    range: '0-9999',
    impact: '对水属性敌人造成额外伤害',
  },
  metalRes: {
    code: 'metalRes',
    name: '金属性抗性',
    displayName: '金属性抗性',
    description: '对金元素攻击的抗性',
    isPercentage: true,
    range: '0-100%',
    impact: '减少受到的金属性伤害',
  },
  woodRes: {
    code: 'woodRes',
    name: '木属性抗性',
    displayName: '木属性抗性',
    description: '对木元素攻击的抗性',
    isPercentage: true,
    range: '0-100%',
    impact: '减少受到的木属性伤害',
  },
  waterRes: {
    code: 'waterRes',
    name: '水属性抗性',
    displayName: '水属性抗性',
    description: '对水元素攻击的抗性',
    isPercentage: true,
    range: '0-100%',
    impact: '减少受到的水属性伤害',
  },
  fireRes: {
    code: 'fireRes',
    name: '火属性抗性',
    displayName: '火属性抗性',
    description: '对火元素攻击的抗性',
    isPercentage: true,
    range: '0-100%',
    impact: '减少受到的火属性伤害',
  },
  earthRes: {
    code: 'earthRes',
    name: '土属性抗性',
    displayName: '土属性抗性',
    description: '对土元素攻击的抗性',
    isPercentage: true,
    range: '0-100%',
    impact: '减少受到的土属性伤害',
  },
} as const
